name: performance
on:
  pull_request_target:
    types:
      - opened
      - edited
    branches:
      - "release/**"
jobs:
  run-performance:
    runs-on: ubuntu-latest
    name: run build and tests
    steps:
      - name: checkout solution
        uses: actions/checkout@v3
      - name: Use Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: build and start solution
        working-directory: ./packages/web
        run: |
          npm ci
          npm run build
          npm run preview --host & npx wait-on http://localhost:3000
      - name: run performance tests
        run: docker run -v "$(pwd):/sitespeed.io" sitespeedio/sitespeed.io:27.8.0 http://localhost:3000 --budget.configPath .github/budget.json -n 1
